### ISSUE TITLE
cool module!

### ISSUE THREAD

**Issue by rjrodger** [mirceaalexandru/seneca-cron#6]
you should npm publish!

**Comment by AdrieanKhisbe** [comment]
@mirceaalexandru Should be closed now: https://www.npmjs.com/package/seneca-cron

**Comment by mirceaalexandru** [comment]
@AdrieanKhisbe Yes, thank you. Need to add more documentation on this.

**Comment by AdrieanKhisbe** [comment]
I forked, and currenlty foking on it:
gitignore, travis so far.

and now on fixing #5 applying latest seneca.

PR coming soon :)

**Comment by mirceaalexandru** [comment]
Great, thank you. I will work (I am hopping tomorrow) on documentation also.
